=== AndrewIsh/mod-ill-ramls/schemas/submission/submission.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Submission",
  "description": "Represents a single interlibrary loan submission",
  "properties": {
    "id": {
      "description": "Unique ID (generated UUID) of the submission",
      "type": "string",
      "$ref": "../../../raml-util/schemas/uuid.schema"
    },
    "userId": {
      "description": "ID of the patron the submission was made by",
      "type": "string",
      "$ref": "../../../raml-util/schemas/uuid.schema"
    },
    "submissionLocation": {
      "description": "The location associated with the submission",
      "type": "string",
      "$ref": "../../../raml-util/schemas/uuid.schema"
    },
    "statusId": {
      "description": "Status of the submission",
      "type": "string",
      "$ref": "../../../raml-util/schemas/uuid.schema"
    },
    "submissionDate": {
      "description": "Date time when the submission was placed",
      "type": "string"
    },
    "requestCount": {
      "description": "A count of the number of requests associated with this submission",
      "type": "string"
    },
    "submissionMetadata": {
      "description": "The ISO18626 JSON metadata used to create the submission",
      "type":  "object",
      "$ref": "submission-metadata.schema"
    },
    "metadata": {
      "type": "object",
      "$ref": "../../../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "additionalProperties": false,
  "required": [
    "userId",
    "submissionLocation",
    "submissionMetadata"
  ]
}

=== AndrewIsh/mod-ill-ramls/examples/submission/submission.json
{
  "id": "cf23adf0-61ba-4887-bf82-956c4aae2260",
  "userId": "346ad017-dac1-417d-9ed8-0ac7eeb886aa",
  "submissionLocation": "1e29e93c-56a6-4072-975a-e5e956e501dd",
  "statusId": "5827b7f7-7038-497c-9863-2c34844ee35a",
  "submissionDate": "2021-06-09T23:11:00-01:00",
  "metadata": {
    "createdDate": "2021-11-19T00:00:00.000+0000",
    "createdByUserId": "28d1057c-d137-11e8-a8d5-f2801f1b9fd1",
    "updatedDate": "2021-11-19T00:00:00.000+0000",
    "updatedByUserId": "28d1057c-d137-11e8-a8d5-f2801f1b9fd1"
  },
  "submissionMetadata": {
    "BibliographicInfo": {
      "SupplierUniqueRecordId": "ETOCRN370903711",
      "TitleOfComponent": "Magnetic resonance in medicine"
    },
    "PublicationInfo": {
      "Publisher": "O'Reilly"
    }
  }
}
